### ISSUE TITLE
Инструкция по установке и ошибки

### ISSUE THREAD

**Issue by homylt** [lintest/TesseractOCR1C#1]
Добрый день. Так и не удалось запустить. Было бы не плохо написать инструкция и порядок установки. Макет TesseractOCR1C  в обработке должен быть пустым?

Тип не определен (AddIn._e5acfc2cf24743ca9b9353454b7b5a2b.TesseractOCR)
{ExternalDataProcessor.Example.Form.xUnitBDD.Form(59)}:ПроверяемоеЗначение = Новый("AddIn." + ИдентификаторКомпоненты + "." + ИмяКомпоненты);
{ExternalDataProcessor.Example.Form.Autotests.Form(18)}:ВК = Ожидается.Тест().Компонента("TesseractOCR").Вернуть();
{(1)}:НаборТестов.Тест_РаспознатьИзображение(xUnitBDD)
{ExternalDataProcessor.Example.Form.RunTests.Form(162)}:Выполнить("НаборТестов." + ГруппаТестов.ИмяМетода + "(xUnitBDD)");
{ExternalDataProcessor.Example.Form.RunTests.Form(178)}:ВыполнитьТест(ТекСтр);
{ExternalDataProcessor.Example.Form.RunTests.Form(63)}:ВыполнитьТесты();

**Comment by lintest** [comment]
Вот работающий пример. Для работы необходимо скачать языковые файлы с сайта Tesseract
https://github.com/lintest/TesseractOCR1C/releases/download/0.2.0.12/TesseractOCR1C.epf

![image](https://user-images.githubusercontent.com/92895/189300773-6a92c2b6-4cdc-480b-9022-f227a99d2dcc.png)

**Comment by lintest** [comment]
@homylt вопрос снят? Закрываю задачу?
